name: hmgroupweb
description: "Ứng dụng công nghệ chuyển đổi số Hoàn Mỹ Group."
publish_to: 'none'
version: 1.4.4

environment:
  sdk: ">=3.2.0 <4.0.0"
macos:
  min_sdk_version: 10.11
dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  permission_handler: ^11.1.0
  cached_network_image: ^3.3.1
  dropdown_search: ^5.0.6
  clipboard: ^0.1.3
  file_picker: ^5.2.0+1
  desktop_webview_window: ^0.2.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  encrypt: ^5.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.3.0
  intl: ^0.18.1
  excel: ^2.1.0
  video_player: ^2.8.1
  crypto: ^3.0.3
  path_provider: ^2.1.1
  pdf: ^3.10.4
  image_picker: ^1.0.4
  location_web: ^4.2.0
  mobile_scanner: ^3.5.5
  geolocator: ^10.1.0
  sqflite: ^2.3.0
  csv: ^5.0.1 
  fl_chart: ^0.66.0
  share_plus: ^7.2.2
  multi_select_flutter: ^4.1.3
  collection: ^1.17.0
  table_calendar: ^3.0.9
  path: ^1.8.0
  flutter_inappwebview: ^6.0.0
  media_kit: ^1.1.10                        
  media_kit_video: ^1.2.4                   
  media_kit_native_event_loop: ^1.0.8   
  media_kit_libs_macos_video: ^1.1.4  
  media_kit_libs_windows_video: ^1.0.9  
  window_manager: ^0.3.8
  package_info_plus: ^4.0.0
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.20 
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  printing: ^5.11.0 
  uuid: ^4.2.1
  confetti: ^0.8.0
  archive: ^3.3.7
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter_nfc_kit: ^3.6.0
  vibration: ^3.1.3
  flutter_spinkit: ^5.2.0
  visibility_detector: ^0.4.0
  qr_flutter: ^4.1.0
  percent_indicator: ^4.2.3
  timeline_tile: ^2.0.0
  dio: ^5.3.2 
  table_sticky_headers: ^2.0.0
  pdfx: ^2.6.0
  image_gallery_saver: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/RobotoCondensed-Regular.ttf
    - assets/iconAI.png
    - assets/hotellogo.png
    - assets/hotellogo2.png
    - assets/appbarvideo.mp4
    - assets/appvideogroup.mp4
    - assets/appvideohotel.mp4
    - assets/appvideogoclean.mp4
    - assets/logo.png
    - assets/logo2.png
    - assets/logo3.png
    - assets/logo4.png
    - assets/dblogo.png
    - assets/zalologo.png
    - assets/zaloviplogo.png
    - assets/timelogo.png
    - assets/homelogo.png
    - assets/checklogo.png
    - assets/linklogo.png
    - assets/ytlogo.png
    - assets/iglogo.png
    - assets/linkedinlogo.png
    - assets/weblogo.png
    - assets/tiktoklogo.png
    - assets/fblogo.png
    - assets/hrlogo.png
    - assets/oalogo.png
    - assets/goodslogo.png
    - assets/officitylogo.png
    - assets/logogoclean.png
    - assets/logokt.png
    - assets/appbackgrid.png
    - assets/appbackgrid.jpg
    - assets/avatar/
    - assets/aivideo/
    - assets/emaillogo.png
    - assets/logoonline.png
    - assets/vidhcm.png 
    - assets/viddream.png
    - assets/vidgoclean.png
    - assets/hopdonglogo.png
    - assets/appvideohopdong.mp4
    - assets/vidhopdong.png
    - assets/logochecklist.png
    - assets/logochecklistPSA.png
    - assets/logochecklistIMCS.png
    - assets/logochecklistMOBI.png
    - assets/logochecklistVANPHU.jpg
    - assets/logochecklistPMC.jpg
    - assets/logochecklistTERRA.jpg
    - assets/logochecklistSAVILLS.jpg
    - assets/logochecklistVNPT.png
    - assets/logochecklistVISAHO.png
    - assets/apphr.mp4
    - assets/logochecklistUSEM.jpg
    - assets/logochecklistHONGKONG.png